---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3140729939-vKb4WN0bcEcA1m1os5vXtBPzafwQ9JAZnzlTPx6
:access_token_secret: tS6DW1SwDSvVO843rEkuWMS0nzWWG0rFvUxE0bZ7HN75D
